
import type { Metadata } from "next";
import { LanguageProvider } from "./context/LanguageContext";
import "./globals.css";
import Nav from "./components/Nav";
import Footer from "./components/Footer";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <LanguageProvider >
      <html lang="en">
        <body>
          <Nav />
          <div className="content mb-0 pb-0">
            {children}
          </div>
          <Footer />
        </body>
      </html>
    </LanguageProvider>
  );
}
